services:
  postgres:
    container_name: postgres
    image: "postgres:15.2"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: "/data/postgres"
    volumes:
      - postgres_data:/data/postgres
    restart: "unless-stopped"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  bot:
    image: ghcr.io/stas12312/my-tickets-bot:latest
    container_name: my-tickets-bot
    env_file:
      - .env
    depends_on:
     postgres:
        condition: service_healthy
  api:
    image: ghcr.io/stas12312/my-tickets-bot:latest
    container_name: my-tickets-api
    entrypoint: python src/server.py
    ports:
      - ${API_IP}:8000
    env_file:
      - .env
    depends_on:
     postgres:
        condition: service_healthy
volumes:
  postgres_data:
    driver: local